
operadores =(
        //Simbolos
        " " => "ESPACIO",
        '"' => "COMILLA_DOBLE",
        "*" => "MULTIPLICACION",
        "+" => "SUMA",
        "-" => "RESTA",
        "/" => "DIVISION",
        "=" => "IGUAL",
        ">" => "MAYOR_QUE",
        "<" => "MENOR_QUE",
        "<= " => "MENOR_IGUAL_QUE",
        ">= " => "MAYOR_IGUAL_QUE",
        "&&" => "OP_AND",
        "||" => "OP_OR",
        "==" => "IGUAL",
        "===" => "IDENTICO",
        "!=" => "DIFERENTE",
        "<>" => "DIFERENT",
        "!==" => "NO_IDENTICO",
        "<=>" => "NAVE_ESPACIAL",
        "??" => "FUSION_NULL",
        "++" => "INCREMENTO",
        "--" => "DECREMENTO",
        "!" => "NOT"
    );
reservada = (
	 	'abstract' => "ABSTRACT",
	 	'and' => "AND",
	 	'array' => "ARRAY",
	 	'as' => "AS",
	 	'break' => "BREAK", 
	 	'callable' => "CALLABLE", 
	 	'case' => "CASE", 
	 	'catch' => "CATCH", 
	 	'class' => "CLASS", 
	 	'clone' => "CLONE", 
	 	'const' => "CONST", 
	 	'continue' => "CONTINUE", 
	 	'declare' => "DECLARE", 
	 	'default' => "DEFAULT", 
	 	'die' => "DIE", 
	 	'do' => "DO", 
	 	'echo' => "ECHO", 
	 	'else' => "ELSE", 
	 	'elseif' => "ELSEIF", 
	 	'empty' => "EMPTY", 
	 	'enddeclare' => "ENDDECLARE", 
	 	'endfor' => "ENDFOR", 
	 	'endforeach' => "ENDFOREACH", 
	 	'endif' => "ENDIF", 
	 	'endswitch' => "ENDSWITCH", 
	 	'endwhile' => "ENDWHILE", 
	 	'eval' => "EVAL", 
	 	'exit' => "EXIT", 
	 	'extends' => "EXTENDS", 
	 	'final' => "FINAL", 
	 	'for' => "FOR", 
	 	'foreach' => "FOREACH", 
	 	'function' => "FUNCTION", 
	 	'global' => "GLOBAL", 
	 	'goto' => "GOTO", 
	 	'if' => "IF", 
	 	'implements' => "IMPLEMENTS", 
	 	'include' => "INCLUDE", 
	 	'include_once' => "INCLUDE ONCE", 
	 	'instanceof' => "INSTANCEOF",
	 	 'insteadof' => "INSTEADOF",
	 	 'interface' => "INTERFACE",
	 	 'isset' => "ISSET",
	 	 'list' => "LIST",
	 	 'namespace' => "NAMESPACE",
	 	 'new' => "NEW",
	 	 'or' => "OR",
	 	 'print' => "PRINT",
	 	 'private' => "PRIVATE",
	 	 'protected' => "PROTECTED",
	 	 'public' => "PUBLIC",
	 	 'require' => "REQUIRE",
	 	 'require_once' => "REQUIRE ONCE",
	 	 'return' => "RETURN", 
	 	 'static' => "STATIC", 
	 	 'switch' => "SWITCH", 
	 	  'throw' => "THROW", 
	 	  'trait' => "TRAIT", 
	 	  'try' => "TRY", 
	 	  'unset' => "UNSET", 
	 	  'use' => "USE", 
	 	  'var' => "VAR", 
	 	  'while' => "WHILE", 
	 	  'xor' => "XOR"
	 );
